name: phone_number
description: Flutter plugin for parsing, formatting and validating international
  phone numbers.
version: 1.0.3
homepage:

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.16.0
  web: ^1.1.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: np.com.rohanshrestha.phone_number
        pluginClass: PhoneNumberPlugin
      ios:
        pluginClass: PhoneNumberPlugin
      web:
        pluginClass: PhoneNumberPlugin
        fileName: src/phone_number_web.dart
